# Generated by Django 5.1.4 on 2025-01-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0002_alter_name_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='profession',
            field=models.CharField(blank=True, choices=[('Writer', 'Writer'), ('Actor', 'Actor'), ('Director', 'Director')], max_length=50, null=True),
        ),
    ]
