# Generated by Django 5.1.4 on 2024-12-29 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cast", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("year_of_production", models.IntegerField()),
                ("length", models.IntegerField()),
                ("imdb_rating", models.FloatField(max_length=3)),
                ("your_rating", models.FloatField(max_length=3)),
                ("thumbnail", models.ImageField(upload_to=None)),
                (
                    "actors",
                    models.ManyToManyField(related_name="actors", to="cast.name"),
                ),
                (
                    "director",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="directors",
                        to="cast.name",
                    ),
                ),
                (
                    "writer",
                    models.ManyToManyField(related_name="writers", to="cast.name"),
                ),
            ],
        ),
    ]
