# Generated by Django 5.1.4 on 2024-12-31 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="imdb_rating",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="products",
            name="your_rating",
            field=models.IntegerField(),
        ),
    ]
