# Generated by Django 5.1.4 on 2025-01-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_imdb_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnails/'),
        ),
    ]
