# Generated by Django 5.1.4 on 2025-01-03 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_products_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='type',
            field=models.CharField(blank=True, choices=[('Movie', 'Movie'), ('TV-Show', 'TV-Show'), ('Set-Com', 'Set-Com')], max_length=50, null=True),
        ),
    ]
