# Generated by Django 5.1.4 on 2025-02-16 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='products',
            name='type',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Movie', 'Movie'), ('TV-Show', 'TV-Show'), ('Set-Com', 'Set-Com')], max_length=50, null=True),
        ),
    ]
